### ISSUE TITLE
ReportCard's toggle is broken

### ISSUE THREAD

**Issue by gabsc9** [redseiko/ComfyMods#102]
ReportCard is a great mod, I truly appreciate it, however, the toggle to make it closed by default on character start doesn't work.
It's a small issue, but it's preferable to have the character start cleaner.

**Comment by redseiko** [comment]
Fixed with commit 5a70a786b7bf81ef78be83b9a9ce0287fabd1109.
Now on Thunderstore as `v1.1.0`.
* https://thunderstore.io/c/valheim/p/ComfyMods/ReportCard/
