### ISSUE TITLE
Feature Request for ReportCard - Show Biome % Coverage of Map

### ISSUE THREAD

**Issue by zylo47** [redseiko/ComfyMods#110]
The beta version of the ReportCard mod showed the pixel count of each biome's coverage of the map. The current version only shows % of that biome explored by the player.

It would be helpful information to be able to see either the total pixel count again or the % of the world that the biome covers (perhaps as a toggle)

**Comment by redseiko** [comment]
New toggle added in v1.2.0: https://thunderstore.io/c/valheim/p/ComfyMods/ReportCard/
