### ISSUE TITLE
Pinnacle - Minor Bug

### ISSUE THREAD

**Issue by zylo47** [redseiko/ComfyMods#111]
When you add a pin with Pinnacle the Y coordinate always shows 0.  In order to see the Y value you have to close the map and re-open it (not just click off the pin and back onto it).

Steps to reproduce
- open map
- drop pin
- see the Y value is 0
- close map
- open map
- click pin and see the Y value is set to the proper value

**Comment by redseiko** [comment]
Fixed with Pinnacle `v1.11.0`.
* https://thunderstore.io/c/valheim/p/ComfyMods/Pinnacle/
