### ISSUE TITLE
Chatter not compatible with StartupAccelerator

### ISSUE THREAD

**Issue by Neoony** [redseiko/ComfyMods#115]
It seems Chatter is not compatible with StartupAccelerator

https://github.com/blaxxun-boop/StartupAccelerator/issues/3

**Comment by redseiko** [comment]
Not fixing. My mod depends on order of patching which StartupAccelerator clobbers. Use the config option to ignore Chatter.

**Comment by TheCavemanOfficial** [comment]
what config option? there is no such option.
