### ISSUE TITLE
Intermission - spacebar reverts to base game hints

### ISSUE THREAD

**Issue by Oosquai** [redseiko/ComfyMods#116]
Hi!  I love Intermission.  I use it to give loading screen tips to explain all the changes I've made with mods on my server for my players.  Pressing spacebar during a loading screen causes the game to advance to the next tip, which is great.  The issue I'm here hoping for help on is that Intermission is allowing this to revert to the base game hints.  Is it possible to have spacebar advance to the next tip from tips.txt please?
Thanks!

**Comment by redseiko** [comment]
This should now be fixed with `v1.8.0`.

https://thunderstore.io/c/valheim/p/ComfyMods/Intermission/

**Comment by Oosquai** [comment]
Works great!  Thank you so much!!
