### ISSUE TITLE
ReportCard Mod Showing Incorrect Percentages

### ISSUE THREAD

**Issue by zylo47** [redseiko/ComfyMods#118]
When the option ShowRawValues is toggled, the map stats are showing incorrect percentages.  The ratio of raw values seems correct but the percent number is wrong.  The percent number seems correct when ShowRawValues is off.

**Comment by redseiko** [comment]
This is intended. The percentage value shown when `ShowRawValues` is toggled is each biome's total area out of the entire world area (`biomeTotal / worldTotal`).

The config option was only added by Comfy request.
