### ISSUE TITLE
Compress: Unable to Open Chests

### ISSUE THREAD

**Issue by searica** [redseiko/ComfyMods#119]
After installing Compress on both the server and client, clients are unable to interact with chests. The `ContentsWithin` mod still correctly pops up a window though (can't recall if the contents in that were correct). 

I don't know if this is intended for use with the current version of Valheim (Bog Witch) or if it's even intended for general use, so I don't know if this should be considered a bug or not. If it is a bug then I'm happy to replicate the issue and provide a log file.

**Comment by redseiko** [comment]
This mod is deprecated.
