### ISSUE TITLE
<Chatter> [Suggestion] Handling for Portal HUD Text Spam

### ISSUE THREAD

**Issue by virtualbjorn** [redseiko/ComfyMods#12]
Would be nice to catch the Portal HUD Text Spam so it doesn't flood the chat window

**Comment by virtualbjorn** [comment]
I think it has something to do with mods that modify portal text

**Comment by redseiko** [comment]
Can you provide a screenshot and steps to reproduce, otherwise I don't really know how to diagnose and handle this case.

**Comment by virtualbjorn** [comment]
![image](https://user-images.githubusercontent.com/19782129/181012135-b8427944-e794-4a8b-bebf-91ea5c19b998.png)

**Comment by virtualbjorn** [comment]
I think it has something to do with this HoverText patch
![image](https://user-images.githubusercontent.com/19782129/181013766-92e5f5e6-7ef2-47e7-828d-47ab3f9688a9.png)

**Comment by virtualbjorn** [comment]
https://github.com/redseiko/ComfyMods/pull/13

**Comment by virtualbjorn** [comment]
Would it be possible to have this reopened for [Enhancements] until your text-base filtering in the coming updates?

**Comment by redseiko** [comment]
Re-opened. I've spent the last few days staring at my own code and wondering how I ever got this to even work in the first place. 😭

**Comment by PaloAlo** [comment]
the portal tag interferes in a big way when you have rare magic portal, odins qol, and chatter together.  odins qol uses hover text (i believe) and with the magic portals it starts spamming the portal tag to the screen, which chatter then reads and spams non-stop to the chat window. lags a player down to about 5 fps when you go near a portal. i've already mentioned it to wackymole. and i think he mentioned it to azumatt. for now i cant use your chatter mod because of the lag its causing.  just thought you should be in the loop on this.

**Comment by virtualbjorn** [comment]
@PaloAlo , @redseiko is still looking into this one for better implementation as my PR didn't pass the tests, it does the job but still needs some more work to make it efficient

**Comment by redseiko** [comment]
Good news, I've made progress on implementing a CustomDrawer within ConfigurationManager to handle embedding a list-of-strings within a string value for BepInEx configuration.

![chatter-text-filter](https://user-images.githubusercontent.com/3688670/190086595-676c4126-7f98-49a6-b733-7b56930f3f57.png)

Still a WIP as I need to choose the correct delimiter as well as generalize the drawer for the other types of messages as well as actually implement the filtering itself.

**Comment by redseiko** [comment]
Finished this feature with the custom drawer and it's now available on Thunderstore as v1.2.0.

https://valheim.thunderstore.io/package/ComfyMods/Chatter/
