### ISSUE TITLE
Error when equip cultivator, conflict with Advize_PlantEverything

### ISSUE THREAD

**Issue by SmurfenAround** [redseiko/ComfyMods#18]
_[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
(wrapper dynamic-method) PieceTable.DMD<PieceTable::UpdateAvailable>(PieceTable,System.Collections.Generic.HashSet`1<string>,Player,bool,bool)
Player.UpdateAvailablePiecesList () (at <9be67623c6d74705a14f96d3a8ff485d>:0)
Player.SetPlaceMode (PieceTable buildPieces) (at <9be67623c6d74705a14f96d3a8ff485d>:0)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::SetupEquipment>(Humanoid)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::EquipItem>(Humanoid,ItemDrop/ItemData,bool)
Player.ToggleEquiped (ItemDrop+ItemData item) (at <9be67623c6d74705a14f96d3a8ff485d>:0)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::UseItem>(Humanoid,Inventory,ItemDrop/ItemData,bool)
Player.UseHotbarItem (System.Int32 index) (at <9be67623c6d74705a14f96d3a8ff485d>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)_

Error when equip cultivator, conflict with Advize_PlantEverything

Advize has been notified as well.

**Comment by SmurfenAround** [comment]
Also conflict with Valweed,valharvest etc,

you are no longer able to see or cultivate said crops from these mods as they disappear from cultivator table.

**Comment by SmurfenAround** [comment]
It also affects Farming skill multi plant function,

When a player has enough skill one can multi plant, no matter what number is show to multi plant when toggled, only 1 will plant, 
Giving error:

_[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
(wrapper dynamic-method) PieceTable.DMD<PieceTable::UpdateAvailable>(PieceTable,System.Collections.Generic.HashSet`1<string>,Player,bool,bool)
Player.UpdateAvailablePiecesList () (at <9be67623c6d74705a14f96d3a8ff485d>:0)
(wrapper dynamic-method) Player.DMD<Player::OnInventoryChanged>(Player)
(wrapper dynamic-method) Inventory.DMD<Inventory::Changed>(Inventory)
(wrapper dynamic-method) Inventory.DMD<Inventory::RemoveItem>(Inventory,string,int)
OdinQOL.Patches.CFC+ConsumeResourcesPatch.Prefix (Player __instance, Piece+Requirement[] requirements, System.Int32 qualityLevel) (at <39442e7e908f47d99a900847d7d22a6f>:0)
(wrapper dynamic-method) Player.DMD<Player::ConsumeResources>(Player,Piece/Requirement[],int)
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacement>(Player,bool,single)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)_




Removal of potterybarn resolves all issues stated above.

**Comment by lightsourced** [comment]
I'm also having this issue, but now with the new SearsCatalog mod. Here is my log -- https://pastebin.com/p7tdkRRR

**Comment by redseiko** [comment]
Tested this just now:

```csharp
  [HarmonyPatch(typeof(PieceTable))]
  static class PieceTablePatch {
    [HarmonyPrefix]
    [HarmonyPatch(nameof(PieceTable.UpdateAvailable))]
    static void UpdateAvailablePrefix(ref PieceTable __instance) {
      while (__instance.m_availablePieces.Count < 4) {
        __instance.m_availablePieces.Add(new());
      }

      foreach (GameObject pieceObj in __instance.m_pieces) {
        Piece piece = pieceObj.GetComponent<Piece>();

        if (piece.m_category != Piece.PieceCategory.All
            && ((int) piece.m_category) >= __instance.m_availablePieces.Count) {
          ZLog.LogWarning($"Piece {piece.m_name} has invalid category {piece.m_category} in {__instance.name}");
          piece.m_category = Piece.PieceCategory.Misc;
        }
      }
    }
  }
 ```
 
 Resulting in:
 
 ```
[Warning:      ZLog] [01/13/2023 00:50:08] Piece $peVinesName has invalid category Max in _CultivatorPieceTable
[Warning:      ZLog] [01/13/2023 00:50:08] Piece $peGlowingMushroomName has invalid category Max in _CultivatorPieceTable
```

Working on a minor update to PotteryBarn and that will include setting these PieceCategory values to something not-max.

**Comment by redseiko** [comment]
Update: it's because PotteryBarn is adding them to a custom category for the Hammer table where-as PlantEverything moves them to the default category in Cultivator.

I'll have a better fix later.

**Comment by redseiko** [comment]
This is fixed in one of the most recent PotteryBarn updates.
