### ISSUE TITLE
[Suggestion] Item Listing

### ISSUE THREAD

**Issue by Canis-Dirus** [redseiko/ComfyMods#19]
Can you add support for another Message type for items being picked up?

**Comment by redseiko** [comment]
Can you be more specific and provide screenshots along with current behavior and requested behavior.

Otherwise i will close this in a few days.

**Comment by Canis-Dirus** [comment]
![image](https://user-images.githubusercontent.com/94489123/194892966-721598e4-2ca6-41d4-bc30-5f7e9cd5927e.png)
In this box I would like a selection for showing items that have been picked up. If I'm in combat I don't always see what was on ground before it gets scooped into the inventory. This would help with "Pick and run" scary situations when fighting more than a few mobs at a time. In order to be less spam for things like wood you could have it buffer and then say picked up 5x Wood, instead of 1x wood many times. 

The game or another mod (not sure which) has a spot in the top left that has this information but its not scrollable and is very slow.

![image](https://user-images.githubusercontent.com/94489123/194894187-b017ed79-c998-4365-b550-1e7d151c7e61.png)

**Comment by redseiko** [comment]
Your idea is probably best suited for another mod that can aggregate that info and then simply emit a chat message which Chatter will pick up.

Chatter's scope is purely UI and displaying content already generated by the game.
