### ISSUE TITLE
[Feature Request] Toggle coordinates in the Pin List Panel

### ISSUE THREAD

**Issue by Abbanon** [redseiko/ComfyMods#23]
Being able to toggle the coordinates/digits in the pin list panel would be good, because then the panel itself could be resized horizontally to take up less space, and still be legible. Would you please consider this for a future mod update?

Current pin list (forced coordinate visibility):
![Screenshot_2](https://user-images.githubusercontent.com/37251822/204129374-ec9da472-9074-455c-b4a0-018c57bb69d1.png)

Mockup of coordinates toggled off: 
![Screenshot_1](https://user-images.githubusercontent.com/37251822/204129310-c403a79c-185e-4341-9d8d-2ea7b1e636b2.png)

**Comment by redseiko** [comment]
Will try to add this in as a toggle for the next update.

**Comment by redseiko** [comment]
Feature added in `v1.8.0` under config option `PinListPanelShowPinPosition`.

https://valheim.thunderstore.io/package/ComfyMods/Pinnacle/
