### ISSUE TITLE
[Feature request] Remember chat channel and color input text accordingly.

### ISSUE THREAD

**Issue by weiler-git** [redseiko/ComfyMods#26]
We chat a lot in /s and to avoid typing it all the time I made a small mod that adds the channel prefix (/s, /say, /p) according to the last used channel if none is specified when sending a new message.
/p is from Smoothbrain’s Groups mods

Would it be possible to have this built into your mod instead?
Adding the same colors to the input text before sending would make it easy to see what channel you are about to send to.
Maybe even some small buttons to change channel for new players who don’t know the slash commands would be nice, as long as it doesn’t harm the otherwise neat and clean design of this mod.

**Comment by redseiko** [comment]
Feature added in v1.3.0 (now published in Thunderstore).

Can be changed via /say /shout /whisper on its own and is reflected in the placeholder text and the color.
Too much work at the moment to add UI button toggle/dropdown list.

Config option added to set initial value at game start.
