### ISSUE TITLE
stability issues

### ISSUE THREAD

**Issue by IAmTheRealGoof** [redseiko/ComfyMods#27]
having this mod enabled is causing stability issues in Valheim.v0.212.7. Sometimes crashing during game, or always on exit.  Disabling/removing this mod restores stability.  Other mods include: 

- Advize-PlantEverything-1.12.0
- Azumatt-Official_BepInEx_ConfigurationManager-17.0.0
- GemHunter1-FastTeleport-1.0.0
- Korppis-ReliableBlock
- MaGic-Quick_Deposit-1.0.1
- mgway-PaddlePower-1.0.2
- MSchmoecker-MultiUserChest-0.3.0
- Neobotics-RequipMe-0.1.3
- Nexus-FarmGrid-0.2.0
- OdinPlus-TripleBronzeJVL-1.1.2
- Oryxen.Valheim.UI.DisplayDayTime
- PenlsSticky-QuickerStack-0.0.1
- Smoothbrain-Evasion-1.0.2
- Smoothbrain-Groups-1.1.11
- Smoothbrain-Sailing-1.1.4
- Smoothbrain-SmoothSave-1.0.0
- TeamHalcyon-TreeRespawn_by_Aedenthorn-0.8.5
- Tekla-ColorfulSigns-5.4.1604
- Tekla-JsonDotNet-13.0.1
- ValheimModding-Jotunn-2.10.0

**Comment by redseiko** [comment]
Provide a LogOutput.log immediately right after a crash otherwise I can't investigate this.
Will close this issue in a few days if no response.
