### ISSUE TITLE
Compress mod

### ISSUE THREAD

**Issue by Percel32** [redseiko/ComfyMods#30]
Hello, maybe I should update the mod to Misty, because I added it to my server and you can't see any difference in its operation.  The problem is that lag occurs even when there are more people in one place..

**Comment by redseiko** [comment]
Both servers and clients need to run the mod for it to work.
Also has not been tested for Mistlands update.

Please try (https://valheim.thunderstore.io/package/ComfyMods/ReturnToSender/) for your server as well.
