### ISSUE TITLE
[Feature Request - Enhuddlement] Compatibility with WackyEpicMMOSystem

### ISSUE THREAD

**Issue by lightsourced** [redseiko/ComfyMods#32]
Would love if you could work in compatibility with WackyEpicMMOSystem. The level text from the mod is hidden by the health bar and cannot be repositioned. The level value and its color is super important with this mod installed.

WackyEpicMMOSystem: https://valheim.thunderstore.io/package/WackyMole/WackyEpicMMOSystem/

**Comment by redseiko** [comment]
Closing this for now as I don't have time to look at compatibility with an external mod.
