### ISSUE TITLE
Rune Magic - Weather Protection BLOCKS all color in dome (conflict)

### ISSUE THREAD

**Issue by GrimmLiberty** [redseiko/ComfyMods#33]
It certainly is an interesting conflict. Rune Magic by hyleanlegend

Not sure if you can/want to sort it out, but Once you set up a standing stone with the weather protection ward, any colored pieces in the circle only show as colored when hovered over with the build hammer and hover moves off target, for like 0.5 seconds, then the color is gone again. I'm not sure what the ward is actually doing to remove rain, wet status effect, etc... but it certainly conflicts... [see below]

If you move the colored object out of range of the dome, like my repeated tests with a cart, do the hammer hover and un-hover, it changes to the correct color and stays that way so long as you don't move it back to the ward. Instantly default color when you do enter it again. 
it does look like he is aware .....   https://www.nexusmods.com/valheim/mods/1359/?tab=bugs 

YOUR mod is Great. So nice to have the colors I want. I can live with the rain if I need to.  LOL
Thank you for your time so far, and any more time you might spend on this mod. I appreciate it! 

-Grimm

**Comment by redseiko** [comment]
Thanks for the report. Hope the other mod author can sort it out. Cheers.
