### ISSUE TITLE
[Pinnacle v1.2.0] Removing a pin leaves the pin text floating over the map.

### ISSUE THREAD

**Issue by awdwyn** [redseiko/ComfyMods#40]
As the title states, in the newest update of Valheim (patch 0.214.2) and Pinnacle 1.2.0 removing any pin (if it has text as well as an icon) leaves the text behind. The text is not attached to the map content, as scrolling the map keeps the text in position relative to the window, not the content. The issue persists when closing and re-opening the map, but is corrected when logging out and back in.

Screenshot included, I have removed two pins and then scrolled the map.
![image](https://user-images.githubusercontent.com/23404043/224879697-4dcbde4e-6a6f-4405-aff8-10e004b9cfd1.png)

**Comment by redseiko** [comment]
Thanks, I totally forgot to test removing a pin. Will look at for a hotfix.

**Comment by awdwyn** [comment]
This mod is making me so happy. You have no idea. I love organizing and being able to use longer pin names, and rename them.. Oh my.

**Comment by redseiko** [comment]
Should be fixed now in v1.2.1 (just pushed it).
Also hot-fix for another bug I found during testing it.
Thanks for the feedback, always glad to hear how useful it is.
If you find any other bugs, feel free to open another issue.
