### ISSUE TITLE
[Feature Request] LicensePlate: hide name when on ship or next to cart

### ISSUE THREAD

**Issue by AiriErminia** [redseiko/ComfyMods#42]
I was hoping you'd be interested in adding an option to hide the vehicle name when you're on/next to it. Or, optionally, just when you're seated/attached to a boat or pulling a cart.

Thanks for all your work.

**Comment by redseiko** [comment]
Added new configuration options that should help with this in v1.2.0 just pushed to Thunderstore.

Will add in when seated/attached in another update if needed.
