### ISSUE TITLE
Pinnacle pin fonts not resizing

### ISSUE THREAD

**Issue by EardwulfC** [redseiko/ComfyMods#46]
Unfortunetly still the same after creating a new player profile. Pin fonts to not resize with the slider. The only thing that appears to change is the map moves from left to right with the slider movement.

From Support Ticket in Comfy Discord

Red's preliminary findings:
It's cause the pin text is now TextMeshPro

Norse SDF
Shader: Norse SDF - Outline

Shader Properties:
ID_OutlineColor = new Color(0f, 0f, 0f, 1f);
ID_OutlineWidth = 0.175f;

**Comment by redseiko** [comment]
Fixed with `v1.6.0`.

https://valheim.thunderstore.io/package/ComfyMods/Pinnacle/
