### ISSUE TITLE
[Issue] Comfy Gizmo Copy not work

### ISSUE THREAD

**Issue by faelBrunnoS** [redseiko/ComfyMods#55]
I'm trying to use Gizmo's new Copy function, but every time I press `P`, this error appears:
```unity
[Info   : Unity Log] 07/24/2023 02:21:05: Setting selected recipe 0

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Gizmo.Patches.PlayerPatch.UpdatePlacementGhostPrefix (Player& __instance, System.Boolean flashGuardStone) (at <4f522afd18f14439ac1eae8564ffe61e>:0)
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacementGhost>(Player,bool)
(wrapper dynamic-method) Player.DMD<Player::LateUpdate>(Player)
```
I am not using any mod other than Gizmo, Server_devcommands and Official_BepInEx_ConfigurationManager.
All are updated to the latest version available through thunderstore.
Gizmo is at version 1.7.2.

**Comment by BruceOfTheBow** [comment]
Thanks for the bug report. I introduced a bug when adding compatibility for one of our ComfyMods, SearsCatalog, that throws this error if it's not installed. I've just pushed v1.7.3 to thunderstore. Please try it out and let me know if you run into any further issues. Thanks!

**Comment by faelBrunnoS** [comment]
Now it's working normally! Thanks for the quick update.
