### ISSUE TITLE
colorful Pieces issue

### ISSUE THREAD

**Issue by snblanke** [redseiko/ComfyMods#56]
Hello!  I am not sure if another mod is making this happen but I used to use this mod with out any issue.  My build pieces hold on to their highlighted integrity colors permanently as I look around.  I love this mod and don't know where else to post about this!

**Comment by redseiko** [comment]
Hi, can you please provide a `LogOutput.log` during a session when this happens.
You can find that by:
1) If you're using Thunderstore Mod Manager go to Settings > Browse profile data > Navigate to BepInEx folder > LogOutput.log
2) If you're using Vortex or just manual install go to Steam > Right-click on Valheim > Manage > Browse local files > Navigate to BepInEx folder > LogOutput.log

That log will contain information on all the mods loaded, their versions as well as any logging info, errors, etc.

Without that I can't help you.

I'll close this issue in 7 days if no response.

**Comment by snblanke** [comment]
I will get on sending you that data, however I haven't seen any error pop up for this issue. It's why it's been so hard to find the problem! Thanks for looking into it! I seriously love this mod

**Comment by snblanke** [comment]
Ok so I have a ton of mods on, I know that can be problematic.  I'm sorry to be a bother but I did not know what else to do!  I attached my log but again, I don't see any errors popping up for this issue.  I did try placing some color this time and the highlighting goes away after I make it a color.  But I don't always want to color everything.  Thanks so much for your time!  I appreciate it very much!

[LogOutput.log](https://github.com/redseiko/ComfyMods/files/12269047/LogOutput.log)

**Comment by redseiko** [comment]
You have alot of mods in here that I'm not familiar with or have never used at all. The best way to narrow down which mod is conflicting with ColorfulPieces highlighting is by:

1) Disable 50% of enabled mods
2) Start the game, check if the problem happens
3) If the problem happens, note the mods that are enabled and go to Step 1
4) If the problem doesn't happen, then the conflicting mod is in the 50% disabled
5) Disable the current 50% enabled mods, enable the 50% previously disabled mods, go to step 2
6) Repeat until you've narrowed down the conflicting mod with ColorfulPieces

How ColorfulPieces does the piece health/integrity highlighting is done here:
https://github.com/redseiko/ComfyMods/blob/main/ColorfulPieces/Patches/WearNTearPatch.cs

I'm using a prefix patch, so another mod is most likely doing the same and they will conflict with each other.
I can look at trying to make a change to make this a non-prefix patch but it would help to know which problematic mod is also doing it to ensure the problem doesn't repeat.

**Comment by snblanke** [comment]
Understood! I have been disabling mods for days now with little luck but I will keep trying! If I find the culprit I will let you know! Just figured I would ask in case you had a solution.  Thanks again for your time!

**Comment by snblanke** [comment]
I figured it out!  It was AzuHoverStats by Azumatt that was making this happen to your mod!  Kinda makes sense honestly lol.  Sorry to have bothered you, and thank you for your help!  I'm just glad I can use your mod without issue again!

**Comment by redseiko** [comment]
Sounds good, thanks for enjoying.
