### ISSUE TITLE
ColorfulPieces: Errors after Hildir patch - forced console opened

### ISSUE THREAD

**Issue by RavECYCLE** [redseiko/ComfyMods#59]
When I launch with it enabled I get a forced console opened that I cant close. 
Tested by disabling the mod and it goes away.
![Screenshot 2023-08-23 180001](https://github.com/redseiko/ComfyMods/assets/42903608/7a4687c3-c536-4c57-bc0e-e01a7d965aab)
[Player.log](https://github.com/redseiko/ComfyMods/files/12421643/Player.log)

log for debug attached.

**Comment by redseiko** [comment]
I'm well aware all mods are broken with the patch. They will be fixed when I have time.
