### ISSUE TITLE
TorchesAndResin not filling Standing blue-burning iron torch

### ISSUE THREAD

**Issue by OfficialDelcos** [redseiko/ComfyMods#70]
As the title said, the current latest version (1.4.0) of TorchesAndResin doesn't refill the Standing blue-burning iron torch.

**Comment by EardwulfC** [comment]
This is intentional as it takes Greydwarf Eyes and not Resin to fill.  As a result we do not support this torch being overfuelled on our server.  This mod is working as intended.
