### ISSUE TITLE
Leaving the edit panel to "Death Icon" won't let you create a new pin

### ISSUE THREAD

**Issue by aaron-yang0327-development** [redseiko/ComfyMods#71]
So I just read valheim's assembly code while trying to work on my mod.

**The important bit:** I found out that when you attempt to create a new pin (through double clicking) it checks if the `m_selectedType` is not equal to the Death pin type if so, pin is created.

Tested it out and looks like that's the cause.

I encountered this bug as well a version or two back but never understood what was causing it.

**Comment by redseiko** [comment]
Fixed as of `v1.5.1`.
