### ISSUE TITLE
EnRoute dependencies

### ISSUE THREAD

**Issue by kevr** [redseiko/ComfyMods#73]
Hello there. I've referenced my own current valheim-based assemblies in the project, but building EnRoute is telling me that some functions being used are not in those assemblies references.

Is there a modified version of `assembly_valheim` or related assemblies that resolve this? I did notice that the project is configured to use `assembly_valheim_publicized`, which I don't have.

Thanks for all of your work on Comfy. All pretty awesome stuff.

**Comment by redseiko** [comment]
I'll only answer this question once: https://valheim-modding.github.io/Jotunn/guides/guide.html#manual-setup

I don't intend to provide any further support for mods not published in Thunderstore.
