### ISSUE TITLE
[Chatter] Chat nonfunctional, breaks eating food and displays 'LeftLabel' 'RightLabel' since new update

### ISSUE THREAD

**Issue by smt923** [redseiko/ComfyMods#81]
Since the latest, current Valheim update something with chat has changed and has broken the Chatter mod, this error occurs when first starting up with chatter enabled

> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object                                                              Stack trace:                                                                                                                                                   Chatter.ContentRowManager.SetupContentRow (Chatter.ContentRow row) (at <7ce56ec2653b4c89b8da510144b2a037>:0)                                                   Chatter.ContentRowManager.CreateContentRow (Chatter.ChatMessage message) (at <7ce56ec2653b4c89b8da510144b2a037>:0)                                             Chatter.Chatter.AddChatMessage (Chatter.ChatMessage message) (at <7ce56ec2653b4c89b8da510144b2a037>:0)                                                         Chatter.ChatPatch.OnNewChatMessagePrefix (System.Int64 senderID, UnityEngine.Vector3 pos, Talker+Type type, UserInfo user, System.String text) (at <7ce56ec2653b4c89b8da510144b2a037>:0)                                                                                                                                      (wrapper dynamic-method) Chat.DMD<Chat::OnNewChatMessage>(Chat,UnityEngine.GameObject,long,UnityEngine.Vector3,Talker/Type,UserInfo,string,string)             Chat.RPC_ChatMessage (System.Int64 sender, UnityEngine.Vector3 position, System.Int32 type, UserInfo userInfo, System.String text, System.String senderAccountId) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)                                                                                                                   System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <834b2ded5dad441e8c7a4287897d63c7>:0)                                                                    Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.                                                                System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <834b2ded5dad441e8c7a4287897d63c7>:0)                                                                    System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <834b2ded5dad441e8c7a4287897d63c7>:0)                                  System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <834b2ded5dad441e8c7a4287897d63c7>:0)                                                             System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <834b2ded5dad441e8c7a4287897d63c7>:0)                                                    System.Delegate.DynamicInvoke (System.Object[] args) (at <834b2ded5dad441e8c7a4287897d63c7>:0)                                                                 RoutedMethod`5[T,U,V,B,K].Invoke (System.Int64 rpc, ZPackage pkg) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)                                                    ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)                                                           ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)                                                                                                                                                       ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, System.String methodName, System.Object[] parameters) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)         Chat.SendText (Talker+Type type, System.String text) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)                                                                 Game.UpdateRespawn (System.Single dt) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)                                                                                Game.FixedUpdate () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

as well as when trying to send a chat line:

> [Error  :   BepInEx] System.NullReferenceException: Object reference not set to an instance of an object                                                         at Chatter.ContentRowManager.SetupContentRow (Chatter.ContentRow row) [0x00016] in <7ce56ec2653b4c89b8da510144b2a037>:0                                        at Chatter.ContentRowManager.CreateContentRow (Chatter.ChatMessage message) [0x0004c] in <7ce56ec2653b4c89b8da510144b2a037>:0                                  at Chatter.ContentRowManager.RebuildContentRows () [0x00035] in <7ce56ec2653b4c89b8da510144b2a037>:0                                                           at Chatter.PluginConfig+<>c.<BindConfig>b__116_8 () [0x00000] in <7ce56ec2653b4c89b8da510144b2a037>:0                                                          at ComfyLib.ConfigFileExtensions+<>c__DisplayClass5_0\`1[T].<OnSettingChanged>b__0 (System.Object _, System.EventArgs _) [0x00000] in <7ce56ec2653b4c89b8da510144b2a037>:0                                                                                                                                                     at BepInEx.Configuration.ConfigEntry`1[T].<.ctor>b__10_0 (System.Object sender, BepInEx.Configuration.SettingChangedEventArgs args) [0x00013] in <5e471ddbeb974684bff43bc61f1b58cb>:0                                                                                                                                         at BepInEx.Configuration.ConfigFile.OnSettingChanged (System.Object sender, BepInEx.Configuration.ConfigEntryBase changedEntryBase) [0x00048] in <5e471ddbeb974684bff43bc61f1b58cb>:0                                                                                                                                       [Info   : Unity Log] 12/14/2023 13:51:03: Saying Normal  a  

when trying to eat with chatter enabled:

> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object                                                              Stack trace:                                                                                                                                                   Chatter.ContentRowManager.CreateContentRow (Chatter.ChatMessage message) (at <7ce56ec2653b4c89b8da510144b2a037>:0)                                             Chatter.Chatter.AddChatMessage (Chatter.ChatMessage message) (at <7ce56ec2653b4c89b8da510144b2a037>:0)                                                         Chatter.MessageHudPatch.ShowMessagePostfix (MessageHud+MessageType type, System.String text) (at <7ce56ec2653b4c89b8da510144b2a037>:0)                         (wrapper dynamic-method) MessageHud.DMD<MessageHud::ShowMessage>(MessageHud,MessageHud/MessageType,string,int,UnityEngine.Sprite)                              Player.Message (MessageHud+MessageType type, System.String msg, System.Int32 amount, UnityEngine.Sprite icon) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)        Player.EatFood (ItemDrop+ItemData item) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)                                                                              Player.ConsumeItem (Inventory inventory, ItemDrop+ItemData item, System.Boolean checkWorldLevel) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)                     Humanoid.UseItem (Inventory inventory, ItemDrop+ItemData item, System.Boolean fromInventoryGui) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)                      (wrapper dynamic-method) InventoryGui.DMD<InventoryGui::OnRightClickItem>(InventoryGui,InventoryGrid,ItemDrop/ItemData,Vector2i)                               InventoryGrid.OnRightClick (UIInputHandler element) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)                                                                  UIInputHandler.OnPointerDown (UnityEngine.EventSystems.PointerEventData eventData) (at <be4ef8fefefb41c4bb415483d0dd2cd7>:0)                                   UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerDownHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <042da27c9af642978a8a5138113c4eed>:0)                                                                                                                             UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <042da27c9af642978a8a5138113c4eed>:0)                                                                             UnityEngine.EventSystems.EventSystem:Update()

this also seems to currently break eating food when chatter is enabled, disabling chatter fixes it for now

![image](https://github.com/redseiko/ComfyMods/assets/3849041/79239c11-c85d-46fc-9b71-4435a2ee897f)

**Comment by redseiko** [comment]
Fixed in `v2.3.0`.
