### ISSUE TITLE
Better config and adding more supported fuels.

### ISSUE THREAD

**Issue by Sketaful** [redseiko/ComfyMods#82]
It would be wonderful if this mod could have a better config allowing us to choose what to fill with fuel and the possibiliy to add fireplace to the things auto-filled. Running this on a server 24/7 make the fuel run out really quickly. Furnaces and stuff isn't needed since they burn so short that server or no server have next to none impact. 

Also, coloured torches should be supported from start, why aren't they?

(I love the mod, it works perfectly with that it does).

**Comment by redseiko** [comment]
You'll need to be specific on which mod.

If you're taking about TorchesAndResin it's coded in a very specific way for use on Comfy-server.

There are probably other mods on Thunderstore (a quick search yields a few) that have the features you want.
