### ISSUE TITLE
No configuration menu - F1 key

### ISSUE THREAD

**Issue by SauceyGit** [redseiko/ComfyMods#9]
Hello! F1 key doesn't bring up the configuration menu. The only color that can be set is in the Config file itself, which means that you have to completely quit Valheim, edit the local config, and then relaunch Valheim in order to use a different color.

**Comment by redseiko** [comment]
You will need a ConfigurationManager mod such as:
https://valheim.thunderstore.io/package/cjayride/ConfigurationManager/
