### ISSUE TITLE
Suggestion: PutMeDown hotkeys

### ISSUE THREAD

**Issue by xerberus333** [redseiko/ComfyMods#91]
Apologies if these look stupid. I couldn't articulate how best to write them down:

_#Hotkey Function type, how many states are available to toggle through for the mod upon pressing the hotkey. Overwrites vanilla hotkey function
1 = vanilla off/on. Mod is off
2 = vanilla on/mod on. Toggles between vanilla auto pick up on, and PutMeDown on
3 = vanilla off/vanilla on/mod on. 3 states, more key presses but you have finer control over pick up states.
HotkeyFunctionType = 3_

Or, something like this:

_#Hotkey to press for toggling between auto pickup presets located within config folder (e.g. OnlyWood.txt, OnlyOwnedSpears.txt, OnlyFarmables.txt, VanillaPickUpAll.txt etc). Can leave blank to disable hotkey/s
SwitchPresetHotkeyNext = Num+
SwitchPresetHotkeyPrevious = Num-_

**Comment by redseiko** [comment]
Added a variant of this feature in v1.2.0 (https://valheim.thunderstore.io/package/ComfyMods/PutMeDown/).

Anything more advanced/configurable requires more effort/complexity/time than I have at the moment.
