### ISSUE TITLE
Failure has occurred while loading a type?

### ISSUE THREAD

**Issue by Sketaful** [redseiko/ComfyMods#94]
I'm running a modpack with 100 mods in it so this might not have the slightest to do with anything wrong with your mod, but maybe you know the problem as soon as you see it.. ?

I added Chatter to the modpack and it seemed to work fine during some local testing. Started up the server running the modpack and logged in and...

If I press ENTER ingame I get the nice looking chatwindow formated as it should with Chatter (not buttons thought). I can write just fine in it, but as soon as I press ENTER to send the chat nothing happens ingame, chatwindow with the text is still just there, waiting to be sent. 
The console spits out repeatedly the same error each time I press enter:*

`[Error  : Unity Log] TypeLoadException: Failure has occurred while loading a type.
Stack trace: (wrapper dynamic-method) Chat.DMD<Chat::InputText>(Chat)
Terminal.SendInput () (at <da52c09f594f4a7480000b7420815ba7>:0)
(wrapper dynamic-method) Chat.DMD<Chat::SendInput>(Chat) Chatter.ChatPanelController.OnChatterTextInputFieldSubmit (System.String input) (at <ca4a447ac370428ca1489405c64efbe8>:0)
UnityEngine.Events.InvokableCall1[T1].Invoke (T1 args0) (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Events.UnityEvent1[T0].Invoke (T0 arg0) (at <ab14d35a27c043688812ae199c64b5aa>:0)
TMPro.TMP_InputField.SendOnSubmit () (at <99900a1f9e2a471c8b46c2c560e4eba9>:0)
TMPro.TMP_InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <99900a1f9e2a471c8b46c2c560e4eba9>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <a01fe238487248d39ba352ec152ec890>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction[T1] functor) (at <a01fe238487248d39ba352ec152ec890>:0)
UnityEngine.EventSystems.EventSystem:Update()`

**Comment by redseiko** [comment]
No idea. There's nothing in the stack trace that shows what's not defining the type.
Chatter on its own works fine so it's another mod causing the issue.

**Comment by Sketaful** [comment]
I. Yeah. I thought so. Guess I have to go through them all again. Thanks
for answering. :)



Den ons 17 apr. 2024 04:15redseiko ***@***.***> skrev:
