### ISSUE TITLE
[Pseudonym] Minus chracter not allowed in character name

### ISSUE THREAD

**Issue by MacharaStormwing** [redseiko/ComfyMods#95]
Valheim allows the minus character ("-", ASCII character 0x2D) but the mod Pseudonym does not.
I think it should be allowed.

Feature Suggestion:
If you already allow changing names of a character the same would be nice for worlds, right?

**Comment by redseiko** [comment]
Fixed as of `v1.4.0` on Thunderstore.
* https://thunderstore.io/c/valheim/p/ComfyMods/Pseudonym/
