### ISSUE TITLE
[SearsCatalog] Tabs partially under items and Q/E labels are off the panel in Ashlands update

### ISSUE THREAD

**Issue by c-oren** [redseiko/ComfyMods#96]
Entire issue description is in the title and attached screenshot for a visual example.
![screenshot_2024-05-18_032924](https://github.com/redseiko/ComfyMods/assets/8764093/ec0d097a-0e35-4ea0-aa32-d0797dcb4d6a)

**Comment by GracefulUni** [comment]
This is due to a mod that isnt updated that is using PieceManager in the mod

**Comment by c-oren** [comment]
Okay, thanks. I'll check for more mod updates (and try to track down which mod is responsible, if it's not updated yet) next time I switch back to my gaming system.

**Comment by c-oren** [comment]
I'll close this for now. I have several mods using PieceManager, at least 2 have recently been updated (with a PieceManager update in their changelog), waiting on others.

Thank you.
