### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by GracefulUni** [redseiko/ComfyMods#97]
Does this mod need to be updated for Ashlands? I dont know if there is any issues as I dont see errors so im not sure

**Comment by redseiko** [comment]
You're going to have be specific in which mod.

**Comment by GracefulUni** [comment]
im sorry i clicked on the github on returntosender and i thought this was the url to it, i apologize

**Comment by GracefulUni** [comment]
Just following up
Does ReturnToSender need be updated for Ashlands due to any changes?
Recently just added your Scenic mod as well to my modpacks to hope fix those annoying znetscene errors so was curious if that needs be updated for ashlands as well?

Thank you for these 2 mods

**Comment by redseiko** [comment]
No update is needed for either.

**Comment by Neoony** [comment]
Why is there 1.2.0 source code here on git, but there is only 1.1.0 on thunderstore
Cant find 1.2.0 dll

**Comment by redseiko** [comment]
> Why is there 1.2.0 source code here on git, but there is only 1.1.0 on thunderstore Cant find 1.2.0 dll

Updated for the latest version just now.
> https://thunderstore.io/c/valheim/p/ComfyMods/ReturnToSender/
